
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button btnPlus;

	private global::Gtk.Button btnMultiply;

	private global::Gtk.Button btnMinus;

	private global::Gtk.Button btnDivide;

	private global::Gtk.Entry entry2;

	private global::Gtk.Entry entry1;

	private global::Gtk.Button btnClear;

	private global::Gtk.Button btnPercentage;

	private global::Gtk.Entry entry3;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.Label label3;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnPlus = new global::Gtk.Button();
		this.btnPlus.WidthRequest = 70;
		this.btnPlus.HeightRequest = 50;
		this.btnPlus.CanFocus = true;
		this.btnPlus.Name = "btnPlus";
		this.btnPlus.UseUnderline = true;
		this.btnPlus.Label = global::Mono.Unix.Catalog.GetString("+");
		this.fixed1.Add(this.btnPlus);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnPlus]));
		w1.X = 132;
		w1.Y = 115;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnMultiply = new global::Gtk.Button();
		this.btnMultiply.WidthRequest = 70;
		this.btnMultiply.HeightRequest = 50;
		this.btnMultiply.CanFocus = true;
		this.btnMultiply.Name = "btnMultiply";
		this.btnMultiply.UseUnderline = true;
		this.btnMultiply.Label = global::Mono.Unix.Catalog.GetString("x");
		this.fixed1.Add(this.btnMultiply);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnMultiply]));
		w2.X = 132;
		w2.Y = 173;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnMinus = new global::Gtk.Button();
		this.btnMinus.WidthRequest = 70;
		this.btnMinus.HeightRequest = 50;
		this.btnMinus.CanFocus = true;
		this.btnMinus.Name = "btnMinus";
		this.btnMinus.UseUnderline = true;
		this.btnMinus.Label = global::Mono.Unix.Catalog.GetString("-");
		this.fixed1.Add(this.btnMinus);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnMinus]));
		w3.X = 219;
		w3.Y = 115;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnDivide = new global::Gtk.Button();
		this.btnDivide.WidthRequest = 70;
		this.btnDivide.HeightRequest = 50;
		this.btnDivide.CanFocus = true;
		this.btnDivide.Name = "btnDivide";
		this.btnDivide.UseUnderline = true;
		this.btnDivide.Label = global::Mono.Unix.Catalog.GetString("/");
		this.fixed1.Add(this.btnDivide);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnDivide]));
		w4.X = 219;
		w4.Y = 173;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry2 = new global::Gtk.Entry();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.fixed1.Add(this.entry2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry2]));
		w5.X = 130;
		w5.Y = 85;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.fixed1.Add(this.entry1);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry1]));
		w6.X = 130;
		w6.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnClear = new global::Gtk.Button();
		this.btnClear.WidthRequest = 70;
		this.btnClear.HeightRequest = 50;
		this.btnClear.CanFocus = true;
		this.btnClear.Name = "btnClear";
		this.btnClear.UseUnderline = true;
		this.btnClear.Label = global::Mono.Unix.Catalog.GetString("Clear all");
		this.fixed1.Add(this.btnClear);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnClear]));
		w7.X = 304;
		w7.Y = 55;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnPercentage = new global::Gtk.Button();
		this.btnPercentage.WidthRequest = 70;
		this.btnPercentage.HeightRequest = 50;
		this.btnPercentage.CanFocus = true;
		this.btnPercentage.Name = "btnPercentage";
		this.btnPercentage.UseUnderline = true;
		this.btnPercentage.Label = global::Mono.Unix.Catalog.GetString("%");
		this.fixed1.Add(this.btnPercentage);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnPercentage]));
		w8.X = 304;
		w8.Y = 115;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry3 = new global::Gtk.Entry();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = false;
		this.entry3.InvisibleChar = '●';
		this.fixed1.Add(this.entry3);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry3]));
		w9.X = 130;
		w9.Y = 230;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Number 1:");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w10.X = 67;
		w10.Y = 55;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Number 2:");
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w11.X = 67;
		w11.Y = 90;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Result:");
		this.fixed1.Add(this.label3);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
		w12.X = 89;
		w12.Y = 235;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 426;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnPlus.Clicked += new global::System.EventHandler(this.OnBtnPlusClicked);
		this.btnMultiply.Clicked += new global::System.EventHandler(this.OnBtnMultiplyClicked);
		this.btnMinus.Clicked += new global::System.EventHandler(this.OnBtnMinusClicked);
		this.btnDivide.Clicked += new global::System.EventHandler(this.OnBtnDivideClicked);
		this.btnClear.Clicked += new global::System.EventHandler(this.OnBtnClearClicked);
	}
}
